name: Daily Web Scraping

on:
  schedule:
    - cron: '0 8 * * *'  # Todos los días a las 8:00 UTC
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 pandas

      - name: Run scraper
        run: |
          mkdir -p data
          python scripts/scrape_prices.py

      - name: Upload CSV
        uses: actions/upload-artifact@v4
        with:
          name: prices-log
          path: data/prices_log.csv
